### ISSUE TITLE
add confirmation prompt for clearing urls

### ISSUE THREAD

**Issue by andrewchar** [sgalizia/StartUp#11]
To easy to miss click and clear entire group by accident. Could add confirmation (pop-up)? prompting user choice before proceeding.

**Comment by Olyve** [comment]
Yeah I could see that, I am going to add it to Milestone 0.3.0 as I think it is a good fix but its not critical. Are you going to take a stab at this one @andrewchar ? If so make sure your fork is up to date and then make the change and make another PR. I would also suggest looking into the `confirm()` function if you want to take this on yourself :)
